title: مسفر
description: 
url: https://misfer.info
lang: ar
txt_dir: rtl
timezone: Asia/Riyadh
txt_posts: مقالات
txt_about: نبذة

permalink: /:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: ar
      txt_dir: rtl

exclude:
  - scripts/
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github/
